name: Run linter and tests

on: [push, pull_request, workflow_dispatch]

jobs:
  lint:
    runs-on: ubuntu-26.04
    steps:
      - name: Install Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e
        with:
          go-version: 1.26.x
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - name: Run linters
        uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a
        with:
          version: v2.10.0

  test:
    strategy:
      matrix:
        platform: [ubuntu-26.04, windows-2025]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        if: success()
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e
        with:
          go-version: 1.26.x
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - name: Run tests
        run: go test ./... -v

  smoke-tests:
    runs-on: ubuntu-26.04
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f87e5991a6d7451dcb8d9637bfbc97413f497069
        with:
          install: true

      - name: Build Docker image and store in cache
        uses: docker/build-push-action@c3c9e263c25d99ce0380d002d59b67737d91b0dc
        with:
          context: .
          push: false
          load: true
          tags: exercism/go-test-runner
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run Tests in Docker
        run: bin/run-tests-in-docker.sh
